#!/usr/bin/env node
process.chdir(__dirname);

var AddCmd = require('./lib/commands/add'),
	RmCmd = require('./lib/commands/rm'),
	ShowCmd = require('./lib/commands/show'),
	git = require('./lib/git');
	
var args = process.argv,
	cmd = args[2],
	otherArgs = args.splice(3, args.length);

var errorHandler = function(err){
	console.error(err.msg);
	process.exit(err.exitCode);
};

var checkCommand = function(){
	switch(cmd){
		case 'add':
			new AddCmd(otherArgs, errorHandler);
			break;

		case 'rm':
			new RmCmd(otherArgs, errorHandler);
			break;

		case 'show':
			new ShowCmd(otherArgs, errorHandler);
			break;

		case 'update':
			git.checkUpdate();
			break;

		default:
			console.log('Usage: dsm [add | rm | show] [args...]');
			break;
	}

	process.exit(0);
};

checkCommand();